// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Time.Repositories;

#nullable disable

namespace TODOApi.Migrations
{
    [DbContext(typeof(EmployeeTimesContext))]
    [Migration("20220401210404_AddLookupTables")]
    partial class AddLookupTables
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Time.Models.EmployeeHours", b =>
                {
                    b.Property<int>("employee_hours_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("employee_hours_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("employee_hours_id"));

                    b.Property<string>("first_name")
                        .HasColumnType("text")
                        .HasColumnName("first_name");

                    b.Property<string>("last_name")
                        .HasColumnType("text")
                        .HasColumnName("last_name");

                    b.HasKey("employee_hours_id")
                        .HasName("pk_employees");

                    b.ToTable("employees", (string)null);
                });

            modelBuilder.Entity("Time.Models.Hours", b =>
                {
                    b.Property<int>("hours_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("hours_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("hours_id"));

                    b.Property<int?>("EmployeeHoursemployee_hours_id")
                        .HasColumnType("integer")
                        .HasColumnName("employee_hoursemployee_hours_id");

                    b.Property<int>("employee_hours_id")
                        .HasColumnType("integer")
                        .HasColumnName("employee_hours_id");

                    b.Property<int>("hours")
                        .HasColumnType("integer")
                        .HasColumnName("hours");

                    b.Property<long>("weekEndingDate")
                        .HasColumnType("bigint")
                        .HasColumnName("week_ending_date");

                    b.HasKey("hours_id")
                        .HasName("pk_hours");

                    b.HasIndex("EmployeeHoursemployee_hours_id")
                        .HasDatabaseName("ix_hours_employee_hoursemployee_hours_id");

                    b.ToTable("hours", (string)null);
                });

            modelBuilder.Entity("Time.Models.Hours", b =>
                {
                    b.HasOne("Time.Models.EmployeeHours", "EmployeeHours")
                        .WithMany("hours")
                        .HasForeignKey("EmployeeHoursemployee_hours_id")
                        .HasConstraintName("fk_hours_employees_employee_hoursemployee_hours_id");

                    b.Navigation("EmployeeHours");
                });

            modelBuilder.Entity("Time.Models.EmployeeHours", b =>
                {
                    b.Navigation("hours");
                });
#pragma warning restore 612, 618
        }
    }
}
